### ISSUE TITLE
Add ros-melodic-rosbridge-suite

### ISSUE THREAD

**Issue by henryymliu** [ros-melodic-arch/ros-melodic-ros-base#1]
Not sure where exactly to post this issue.
`ros-kinetic-rosbridge-suite` exists in the AUR, is it possible to add the `melodic` equivalent?

**Comment by bionade24** [comment]
We could pack it, but I have now ROS2 installations, so could you please test it then?

**Comment by henryymliu** [comment]
I made my own PKGBUILDs in the meantime, so is it better that I test with those and then give them to you when ready?

**Comment by bionade24** [comment]
No Problem. Will add our specific thing, test  build and publish. Just poste the PKGBUILD on a pastebin.

**Comment by henryymliu** [comment]
Hey, a few updates for now:

- Because of https://github.com/RobotWebTools/rosbridge_suite/issues/371, `python-tornado` will not work with `ros-melodic-rosbridge-server` as it is too new. Currently figuring out a way to use an equivalent of `pip install tornado==4.5.3` in PKGBUILD; I'm pretty new to this whole Arch thing so I'm open to any suggestions of installing that specific version of `tornado`.

- It looks like the other melodic packages involve downloading tarballs instead of cloning, so I'll update my current PKGBUILDs to use tarballs and checksums instead.

**Comment by henryymliu** [comment]
Don't have much time in the next few days, so I'll leave these WIP PKGBUILDs:
Confirmed to be working with my limited use case, at least.

[ros-melodic-rosapi](https://pastebin.com/vKA9qkJi)

[ros-melodic-rosauth](https://pastebin.com/xwBNpZTZ)

[ros-melodic-rosbridge-library](https://pastebin.com/kPzH5VEG)

[ros-melodic-rosbridge-msgs](https://pastebin.com/jBBeRKSk)

[ros-melodic-rosbridge-server](https://pastebin.com/gh84tfEL) <- heavily WIP

[ros-melodic-rosbridge-suite](https://pastebin.com/UxLuisSV)

**Comment by acxz** [comment]
If the package requires a specific older version, another package can be created like `python-tornado-4.5.3` in the AUR. Something similar has been done to the gazebo package requiring version 1.9 of ogre instead of the latest version, 1.12 or something.

I would rather prefer getting the upstream devs in the loop to add support for the latest version of their dependencies, however, I also understand that the fix might be a bit hard or that upstream isn't focusing on the issue.

**Comment by henryymliu** [comment]
Yeah, from that linked issue it looks like they don't want to support a newer version.

**Comment by bionade24** [comment]
Think this is caused my the ros releases and heavily changes in the library. ROS wouldn'nt do the major changes when older distros ship the old version

**Comment by acxz** [comment]
I went ahead and created the package and required dependencies for this request. I have checked that they build and compile but have not tested them running. Will close this issue once they get put on the AUR.

- [ ] [ros-melodic-rosapi](https://github.com/ros-melodic-arch/ros-melodic-rosapi)
- [ ] [ros-melodic-rosauth](https://github.com/ros-melodic-arch/ros-melodic-rosauth)
- [ ] [ros-melodic-rosbridge-library](https://github.com/ros-melodic-arch/ros-melodic-rosbridge-library)
- [x] [ros-melodic-rosbridge-msgs](https://github.com/ros-melodic-arch/ros-melodic-rosbridge-msgs)
- [ ] [ros-melodic-rosbridge-server](https://github.com/ros-melodic-arch/ros-melodic-rosbridge-server)
- [ ] [ros-melodic-rosbridge-suite](https://github.com/ros-melodic-arch/ros-melodic-rosbridge-suite)

**Comment by acxz** [comment]
Since the syncing has been taking a while, I have created these packages on the AUR.

@henryymliu Sorry for taking so long, these packages are finally up on the AUR!

@bionade24 You can email me so that I can transfer ownership from the packages over to you. I apologize for any inconveniences this may cause, but I wanted to get this issue closed. Just transferred over ownership.
